- name: brave
  tags:
    - install
    - brave
  block:
    - name: Install curl
      apt:
        name: curl
        state: present
    - name: Download Brave's GPG key
      command:
        cmd: "curl -fsSLo /usr/share/keyrings/brave-browser-archive-keyring.gpg https://brave-browser-apt-release.s3.brave.com/brave-browser-archive-keyring.gpg"
    - name: Add Brave's APT repository
      command:
        cmd: "echo 'deb [signed-by=/usr/share/keyrings/brave-browser-archive-keyring.gpg] https://brave-browser-apt-release.s3.brave.com/ stable main' | tee /etc/apt/sources.list.d/brave-browser-release.list"
    - name: Update APT cache
      apt:
        update_cache: yes
    - name: Install Brave browser
      apt:
        name: brave-browser
        state: present