- name: fira_font
  tags:
    - install
    - fira_font
  block:
  - name: Install required packages for Fira Code font
    apt:
      name:
        - fontconfig
        - unzip
      state: present
  - name: Set up Fira Code font requirement
    shell: sudo add-apt-repository universe
  - name: Create fonts directory
    ansible.builtin.file:
      path: /usr/local/share/fonts/NerdFonts
      state: directory
      mode: '0755'
  - name: Download FiraCode Nerd Font
    get_url:
      url: https://github.com/ryanoasis/nerd-fonts/releases/download/v2.1.0/FiraCode.zip
      dest: /tmp/FiraCode.zip
  - name: Unzip FiraCode Nerd Font
    unarchive:
      src: /tmp/FiraCode.zip
      dest: /usr/local/share/fonts/NerdFonts
      remote_src: yes
  - name: Update font cache
    command: fc-cache -f -v
  - name: Install dconf-cli and dbus-x11
    apt:
      name:
        - dconf-cli
        - dbus-x11
      state: present
    become: yes
  - name: Set GNOME Terminal font to FiraCode Nerd Font
    ansible.builtin.shell: >
      dconf write /org/gnome/terminal/legacy/profiles:/$(dconf list /org/gnome/terminal/legacy/profiles:/ | grep '^:.*:$/')font "'FiraCode Nerd Font Mono'"