- name: helix
  tags:
    - install
    - helix
  block:
  - name: Add Helix Editor PPA
    ansible.builtin.apt_repository:
      repo: ppa:maveonair/helix-editor
      state: present
  - name: Install Helix editor
    ansible.builtin.apt:
      name: helix
      state: present