- name: obsidian
  tags:
    - install
    - obsidian
  block:
  - name: Download Obsidian
    get_url:
      url: https://github.com/obsidianmd/obsidian-releases/releases/download/v1.1.16/obsidian_1.1.16_amd64.snap
      dest: /home/pablovarela/Downloads/obsidian.snap
    become: true
  - name: Install Obsidian
    shell: sudo snap install --dangerous /home/pablovarela/Downloads/obsidian.snap --classic
    become: true