- name: python
  tags:
    - install
    - python
  block:
  - name: Install Python3
    apt:
      name: [python3-pip]
    become: true
    become_method: sudo
  - name: Install Black formatter
    shell: pip install Black
  - name: Install Virtualenv
    shell: pip install Virtualenv